#!/usr/bin/python3
import subprocess
import os.path
import pprint

def poop(file):
    if 'root' in file:
        link = file.replace('root', '')
    elif 'home' in file:
        link = os.path.join(os.path.expanduser('~'), '.' + file[5:])
    else:
        return

    if os.path.islink(link):
        print(f'you may want to remove symlink {link}')
hook = os.path.split(__file__)[-1]
if hook == 'post-commit':
    old_commit = 'HEAD~1'
elif hook == 'post-merge':
    old_commit = 'ORIG_HEAD'
k = subprocess.run(["git", "diff", old_commit, 'HEAD', '--name-status'],
        stdout=subprocess.PIPE, encoding='UTF-8')
lines = k.stdout.split('\n')
for line in lines:
    if not line:
        continue
    status = line.split('\t')
    if status[0] == 'A':
        continue
    #pprint.pprint(status)
    if status[0] == 'D':
        poop(status[1])
    if status[0][0] == 'R':
        poop(status[1])
